services:
  api-dev:
    build:
      context: ./src/HippoExchange.Api
      dockerfile: Dockerfile.dev
    image: hippoexchange/api-dev:latest
    container_name: hippoexchange-api-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Mongo__ConnectionString: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
      Mongo__DatabaseName: "${MONGO_DB_NAME}"
    volumes:
      - .:/workspace
    ports:
      - "8082:80"   # host 8082 → container 80
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_PASSWORD}"
