services:
  mongo:
    image: mongo:6
    container_name: hippoexchange-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass
      MONGO_INITDB_DATABASE: hippo-exchange
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2-18
    container_name: hippoexchange-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://devuser:devpass@mongo:27017/hippo-exchange?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: devuser
      ME_CONFIG_BASICAUTH_PASSWORD: devpass
    ports:
      - "8082:8081"
    depends_on:
      - mongo

  api:
    build:
      context: ./src/HippoExchange.Api
      dockerfile: Dockerfile.dev
    container_name: hippoexchange-api
    working_dir: /workspace
    command: >
      sh -c "dotnet restore src/HippoExchange.Api/HippoExchange.Api.csproj &&
             dotnet run --project src/HippoExchange.Api/HippoExchange.Api.csproj --urls http://0.0.0.0:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Mongo__ConnectionString: "mongodb://devuser:devpass@mongo:27017/?authSource=admin"
      Mongo__DatabaseName: "hippo-exchange"
      CLOUDINARY_URL: "${CLOUDINARY_URL:?CLOUDINARY_URL is required}"
      CLERK__ISSUER: "${CLERK__ISSUER:-https://in-husky-23.clerk.accounts.dev}"
      CLERK__AUDIENCE: "${CLERK__AUDIENCE:-authenticated}"
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    image: node:20
    container_name: hippoexchange-frontend
    working_dir: /app
    command: >
      sh -c "corepack enable pnpm &&
             pnpm install &&
             pnpm dev --host 0.0.0.0 --port 3000"
    environment:
      PNPM_HOME: /pnpm-store
      PATH: /pnpm-store:$PATH
      VITE_API_BASE_URL: "${VITE_API_BASE_URL:-http://localhost:8080}"
      VITE_CLERK_PUBLISHABLE_KEY: "${VITE_CLERK_PUBLISHABLE_KEY:?VITE_CLERK_PUBLISHABLE_KEY is required}"
      VITE_CLERK_FRONTEND_API: "${VITE_CLERK_FRONTEND_API:?VITE_CLERK_FRONTEND_API is required}"
      VITE_CLERK_JWT_TEMPLATE: "${VITE_CLERK_JWT_TEMPLATE:-}"
      PNPM_YES: "true"
      CI: "true"
    volumes:
      - ../the-hippo-exchange:/app
      - pnpm-store:/pnpm-store
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pnpm-store:
  frontend-node-modules:
