services:
  api:
    profiles: ["prod"]
    build:
      context: ./src/HippoExchange.Api
      dockerfile: Dockerfile
    image: hippoexchange/api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Mongo__ConnectionString: "mongodb://${MONGO_PROD_USERNAME}:${MONGO_PROD_PASSWORD}@mongodb:27017/?authSource=admin"
      Mongo__Database: "${MONGO_DB_NAME}"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_PROD_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PROD_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: