services:
  api:
    profiles: ["prod"]
    build:
      context: ./src/HippoExchange.Api
      dockerfile: Dockerfile
    image: hippoexchange/api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Mongo__ConnectionString: "mongodb://${MONGO_PROD_USERNAME}:${MONGO_PROD_PASSWORD}@mongo:27017/?authSource=admin"
      Mongo__Database: "${MONGO_DB_NAME}"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data: